management:
  endpoints:
    enabled-by-default: true
    web:
       exposure:
          include: prometheus
  endpoint:
    info:
      enabled: true
  metrics:
     export:
        defaults:
           enabled: true
resilience4j.retry:
    configs:
        default:
            maxAttempts: 3
            waitDuration: 1s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException.NotFound
    instances:
        getOrdersWithRetry:
            baseConfig: default
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            minimumNumberOfCalls: 4
            permittedNumberOfCallsInHalfOpenState: 2
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 30s
            failureRateThreshold: 20
            slidingWindowSize: 10
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException.NotFound            
    instances:
        getOrdersWithCircuit:
            baseConfig: default
resilience4j.bulkhead:
    configs:
        default:
            maxWaitDuration: 1000ms
            maxConcurrentCalls: 1
    instances:
        getOrdersWithBulkhead:
            baseConfig: default